### ISSUE TITLE
大佬你好，训练时应该用model还是model_full呀

### ISSUE THREAD

**Issue by tianwangchn** [YukMingLaw/tf2-yolo-nano#2]
model_full中的expension如果设置为1，decay = 0.001，是不是就是model了吧。

**Comment by YukMingLaw** [comment]
两个都是可以用的。model_full.py是为了部署到边缘设备的时候需要有个转换过程，如果带了自定义层的话转换起来比较困难，我就全部展开了而已。expension是一个超参数，你可以自己实验下哪个最好，按照论文给出的模型参数量是4M，对应的expension是0.75。

**Comment by tianwangchn** [comment]
谢谢大佬，我准备在嵌入式设备上用YOLOnano，然后在github上建一个项目，可以quote您的代码吗，我会在References里面标明来源的。

**Comment by YukMingLaw** [comment]
ok的，期待你的作品！

**Comment by tianwangchn** [comment]
谢谢您大佬~

**Comment by YukMingLaw** [comment]
你好，我更新了代码，加入了图片色彩预处理，比如锐化，亮度，对比度等等，也加入了图片旋转以及镜像。图像随机裁剪我删除了，因为会把一些小目标放大，导致对小目标的检测精度下降。然后就是学原生yolov3，使用多尺度input做训练，recall值提高了不少，但是使用这一技巧就得把网络中的FCA模块关闭。你可以使用新的代码进行训练实验。

**Comment by tianwangchn** [comment]
好嘞，谢谢大佬的update。之前的代码我初步在嵌入式上面调通了，CPU是四核cortexA53，预测单张图片能够达到650ms，之前用原生yolov3单张图片则需要3.5s。因为应用不需要实时的图像目标检测，所以目前的性能很好了，大佬贡献的模型很好用，谢谢大佬。

**Comment by tianwangchn** [comment]
大佬您好，我还想请教一个关于输入图片通道的问题，因为应用场景输入图片是单通道灰度图，目前model_full.py和YoloGenerator.py里面默认是3通道，因为cv2.imread默认转成了3通道所以我就没管。如果我把模型改成单通道输入的话还可以做哪些优化呢，我准备试试改成单通道能不能提高性能。

**Comment by YukMingLaw** [comment]
对于网络推理阶段来说性能提高不大，输入层无论是1通道还是3通道，在第一次卷积的时候都会变成12通道的特征图，后面的卷积计算时间是一样的。你用什么框架进行推理的？可以尝试下使用量化模型来做推理。

**Comment by tianwangchn** [comment]
谢谢大佬的回复，我目前就是用的yoloNano返回的test_model进行推理的。我试过用tflite converter 把训练后的权重量化成int8然后用tflite interpreter推理，但是因为目前的tflite interpreter默认是单线程（下面链接），所以反而慢了很多。其实现在的推理时间对于我的应用来说已经很好了。
https://github.com/tensorflow/tensorflow/issues/35784

**Comment by YukMingLaw** [comment]
可以了解下TVM，可以在arm的gpu跑，我也准备开个坑hh

**Comment by tianwangchn** [comment]
哈哈哈好，谢谢大佬~~

**Comment by tianwangchn** [comment]
大佬不好意思，，之前说在嵌入式上实现YOLOnano，现在实现了。但是征求了老师的意见，不让开坑因为对网络结构做了些改动。最终结果，输入图像大小256*256，单通道，在Orange pi 3 (CPU全志H6 四核Cortex A53@1.8GHz)上单帧推理时间520ms左右，用GTX1060 单帧推理时间40ms左右，单目标检测准确度很高93%左右，比原版YOLOV3 的90%还高。
嵌入式linux 上用的tensorflow2 aarch64版本，https://github.com/lhelontra/tensorflow-on-arm/releases/
anchor用k-means重新生成过。

**Comment by YukMingLaw** [comment]
good job!!
